require 'rubygems'
require 'open-uri'
require 'date'
require 'cgi'
require 'hpricot'
require 'chronic'
require 'ruby-debug'
require 'xmlsimple'

require File.dirname(__FILE__) + '/imdb/optional_logger'
require File.dirname(__FILE__) + '/imdb/imdb_search'
require File.dirname(__FILE__) + '/imdb/imdb_movie'
require File.dirname(__FILE__) + '/imdb/imdb_profile'
require File.dirname(__FILE__) + '/imdb/imdb_image'
require File.dirname(__FILE__) + '/string_extensions'
require File.dirname(__FILE__) + '/file_extensions'
require File.dirname(__FILE__) + '/object_extensions'